services:
  delay-api:
    build: .
    container_name: delay-api
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3101
    expose:
      - "3101"
    networks:
      - devops-edge

networks:
  devops-edge:
    external: true
    name: devops-edge
